[project]
name = "dev1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "docling>=2.118.0",
    "fasttext-wheel>=0.9.2",
    "numpy>=2.4.6",
    "openai-whisper>=20250625",
    "sentence-transformers>=5.6.1",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
    "jupyter>=1.1.1",
]
